<script setup lang="ts">
import { computed, defineAsyncComponent } from "vue";
import type { CommandAuthority, CommandPort } from "../operations/command-port";
import type { MetricSeriesView, OperationsSnapshot, PositionView } from "../operations/operations-port";

type OperationsPane = "overview" | "positions" | "orders" | "signals" | "activity" | "sources";
const props = defineProps<{
  snapshot: OperationsSnapshot;
  activePane: OperationsPane;
  connectionLabel: string;
  stale: boolean;
  authority: CommandAuthority;
  port: CommandPort;
  selectedSignalId: string;
  selectedOrderId: string;
  selectedMetricId: string;
}>();
const emit = defineEmits<{
  authority: [authority: CommandAuthority];
  explore: [];
  selectSignal: [id: string];
  selectOrder: [id: string];
  selectMetric: [id: string];
}>();
const TimeSeriesChart = defineAsyncComponent(() => import("./TimeSeriesChart.vue"));
const NewOrderTicket = defineAsyncComponent(() => import("./NewOrderTicket.vue"));

const selectedSignal = computed(() => props.snapshot.signals.find((item) => item.id === props.selectedSignalId) ?? props.snapshot.signals[0]);
const selectedOrder = computed(() => props.snapshot.orders.find((item) => item.clientOrderId === props.selectedOrderId) ?? props.snapshot.orders[0]);
const selectedMetric = computed(() => props.snapshot.metrics.find((item) => item.id === props.selectedMetricId) ?? props.snapshot.metrics[0]);
const selectedSignalSeries = computed<MetricSeriesView | undefined>(() => {
  const signal = selectedSignal.value;
  if (!signal) return undefined;
  const observedAt = new Date(props.snapshot.observedAt).getTime();
  return {
    id: `signal-${signal.id}`,
    label: signal.hypothesis,
    unit: "%",
    tone: signal.state === "blocked" ? "coral" : signal.state === "eligible" ? "green" : "cyan",
    points: signal.trace.map((point) => ({ timestamp: new Date(observedAt + point.offsetSeconds * 1_000).toISOString(), value: point.valueBps / 100 })),
    referenceLines: [{ label: "50%", value: 50, tone: "neutral" }],
  };
});
const grossUtilization = computed(() => {
  const gross = BigInt(props.snapshot.risk.grossExposureMicros);
  const limit = BigInt(props.snapshot.risk.grossLimitMicros);
  return limit === 0n ? 0 : Number((gross * 1_000_000n) / limit) / 1_000_000;
});
const unrealizedTotal = computed(() => props.snapshot.positions.reduce((total, position) => total + BigInt(position.unrealizedPnlMicros), 0n));
const marketValueTotal = computed(() => props.snapshot.positions.reduce((total, position) => total + absolute(BigInt(position.marketValueMicros)), 0n));
const dayPnlTotal = computed(() => props.snapshot.positions.reduce((total, position) => total + BigInt(position.dayPnlMicros ?? "0"), 0n));

function strategyName(id: string): string { return props.snapshot.strategies.find((item) => item.id === id)?.name ?? id; }
function absolute(value: bigint): bigint { return value < 0n ? -value : value; }
function money(micros: string | bigint, signed = false): string {
  const value = BigInt(micros);
  const negative = value < 0n;
  const absoluteValue = negative ? -value : value;
  const roundedCents = (absoluteValue + 5_000n) / 10_000n;
  const dollars = roundedCents / 100n;
  const cents = roundedCents % 100n;
  const prefix = negative ? "-" : signed ? "+" : "";
  const whole = new Intl.NumberFormat("en-US", { maximumFractionDigits: 0 }).format(dollars);
  return `${prefix}$${whole}${dollars < 100n || cents !== 0n ? `.${cents.toString().padStart(2, "0")}` : ""}`;
}
function quantity(micros: string): string {
  const value = BigInt(micros);
  const negative = value < 0n;
  const absoluteValue = negative ? -value : value;
  const whole = new Intl.NumberFormat("en-US", { maximumFractionDigits: 0 }).format(absoluteValue / 1_000_000n);
  const fraction = (absoluteValue % 1_000_000n).toString().padStart(6, "0").replace(/0+$/, "");
  return `${negative ? "-" : ""}${whole}${fraction ? `.${fraction}` : ""}`;
}
function percent(bps: number): string { return `${(bps / 100).toFixed(1)}%`; }
function ratioBps(numerator: string, denominator: bigint): number {
  if (denominator === 0n) return 0;
  return Number((BigInt(numerator) * 1_000_000n) / denominator) / 100;
}
function positionCostMicros(position: PositionView): bigint { return (absolute(BigInt(position.quantityMicros)) * BigInt(position.averagePriceMicros)) / 1_000_000n; }
function positionOpenBps(position: PositionView): number { return ratioBps(position.unrealizedPnlMicros, positionCostMicros(position)); }
function shortId(id: string): string { return id.length <= 14 ? id : `${id.slice(0, 6)}…${id.slice(-4)}`; }
</script>

<template>
  <div class="operations-pane">
    <template v-if="activePane === 'overview'">
      <section class="metric-strip" aria-label="Account summary"><dl>
        <div><dt>Gross exposure</dt><dd>{{ money(snapshot.risk.grossExposureMicros) }}</dd><small>{{ (grossUtilization * 100).toFixed(1) }}% of limit</small></div>
        <div><dt>Unrealized P&amp;L</dt><dd :class="{ negative: unrealizedTotal < 0n }">{{ money(unrealizedTotal, true) }}</dd><small>{{ snapshot.positions.length }} positions</small></div>
        <div><dt>Active orders</dt><dd>{{ snapshot.orders.length }}</dd><small>{{ snapshot.risk.pendingReconciliations }} unreconciled</small></div>
        <div><dt>Orders today</dt><dd>{{ snapshot.risk.dailyOrderCount }} / {{ snapshot.risk.dailyOrderLimit }}</dd><small>Account limit</small></div>
        <div><dt>Source lag</dt><dd :class="{ caution: snapshot.risk.sourceLagMs > 2_000 }">{{ snapshot.risk.sourceLagMs.toLocaleString() }}ms</dd><small>Worst source</small></div>
      </dl></section>
      <section class="telemetry-section"><header class="section-header"><h1>Portfolio telemetry</h1><div class="metric-tabs" role="tablist" aria-label="Portfolio metric"><button v-for="metric in snapshot.metrics" :key="metric.id" role="tab" :aria-selected="selectedMetric?.id === metric.id" @click="emit('selectMetric', metric.id)">{{ metric.label }}</button></div></header><TimeSeriesChart v-if="selectedMetric" :series="selectedMetric" /><p v-else class="empty-state">No telemetry series</p></section>
      <section class="account-register" aria-label="Account runtime"><dl><div><dt>Capital gate</dt><dd :class="snapshot.risk.capitalGate === 'authorized' ? 'positive' : 'caution'">{{ snapshot.risk.capitalGate }}</dd></div><div><dt>Reserved gross</dt><dd>{{ money(snapshot.risk.reservedGrossMicros) }}</dd></div><div><dt>Open incidents</dt><dd>{{ snapshot.risk.openIncidents }}</dd></div><div><dt>Sequence</dt><dd>{{ snapshot.sequence.toLocaleString() }}</dd></div><div><dt>Checkpoint</dt><dd>{{ snapshot.risk.checkpointAgeMs }}ms</dd></div></dl></section>
    </template>

    <section v-else-if="activePane === 'positions'" class="pane-section" aria-labelledby="positions-heading"><header class="pane-heading"><div><h1 id="positions-heading">Positions</h1><span>{{ snapshot.positions.length }} open</span></div><time :datetime="snapshot.observedAt">Marks {{ connectionLabel.toLowerCase() }}</time></header><div class="position-summary"><dl><div><dt>Market value</dt><dd>{{ money(marketValueTotal) }}</dd></div><div><dt>Open P&amp;L</dt><dd :class="unrealizedTotal >= 0n ? 'positive' : 'negative'">{{ money(unrealizedTotal, true) }}</dd></div><div><dt>Day P&amp;L</dt><dd :class="dayPnlTotal >= 0n ? 'positive' : 'negative'">{{ money(dayPnlTotal, true) }}</dd></div><div><dt>Gross limit</dt><dd>{{ money(snapshot.risk.grossLimitMicros) }}</dd></div></dl></div><div class="table-scroll" tabindex="0" aria-label="Positions. Scroll horizontally for value and change columns."><table class="positions-table"><thead><tr><th>Instrument</th><th>Strategy</th><th class="number">Quantity</th><th class="number">Average</th><th class="number">Mark</th><th class="number">Market value</th><th class="number">Open P&amp;L</th><th class="number">Open %</th><th class="number">Day P&amp;L</th><th class="number">Day %</th><th class="number">Mark age</th></tr></thead><tbody><tr v-for="position in snapshot.positions" :key="`${position.instrument}:${position.strategy}`"><th>{{ position.instrument }}</th><td>{{ strategyName(position.strategy) }}</td><td class="number">{{ quantity(position.quantityMicros) }}</td><td class="number">{{ money(position.averagePriceMicros) }}</td><td class="number">{{ money(position.markPriceMicros) }}</td><td class="number">{{ money(position.marketValueMicros) }}</td><td class="number" :class="BigInt(position.unrealizedPnlMicros) >= 0n ? 'positive' : 'negative'">{{ money(position.unrealizedPnlMicros, true) }}</td><td class="number" :class="positionOpenBps(position) >= 0 ? 'positive' : 'negative'">{{ percent(positionOpenBps(position)) }}</td><td class="number" :class="BigInt(position.dayPnlMicros ?? '0') >= 0n ? 'positive' : 'negative'">{{ money(position.dayPnlMicros ?? '0', true) }}</td><td class="number" :class="(position.dayChangeBps ?? 0) >= 0 ? 'positive' : 'negative'">{{ percent(position.dayChangeBps ?? 0) }}</td><td class="number">{{ position.freshnessMs }}ms</td></tr></tbody></table></div></section>

    <section v-else-if="activePane === 'orders'" class="pane-section" aria-labelledby="orders-heading"><header class="pane-heading"><div><h1 id="orders-heading">Orders</h1><span>{{ snapshot.orders.length }} active</span></div><time :datetime="snapshot.observedAt">OMS sequence {{ snapshot.sequence.toLocaleString() }}</time></header><div class="orders-grid"><Suspense><NewOrderTicket :authority="authority" :port="port" :snapshot="snapshot" :stale="stale" @authority="emit('authority', $event)"/><template #fallback><div class="ticket-loading">Loading order ticket</div></template></Suspense><section class="active-orders" aria-labelledby="active-orders-heading"><header class="section-header"><h2 id="active-orders-heading">Active orders</h2><span>{{ snapshot.orders.length }}</span></header><div class="order-register"><button v-for="order in snapshot.orders" :key="order.clientOrderId" :class="{ selected: selectedOrder?.clientOrderId === order.clientOrderId }" @click="emit('selectOrder', order.clientOrderId)"><span :data-side="order.side">{{ order.side }}</span><strong>{{ order.instrument }}</strong><b>{{ order.state.replaceAll('_', ' ') }}</b><small>{{ strategyName(order.strategy) }}</small><code>{{ shortId(order.clientOrderId) }}</code></button></div><dl v-if="selectedOrder" class="order-detail"><div><dt>Venue</dt><dd>{{ selectedOrder.venue }}</dd></div><div><dt>Quantity</dt><dd>{{ quantity(selectedOrder.quantityMicros) }}</dd></div><div><dt>Filled</dt><dd>{{ quantity(selectedOrder.filledQuantityMicros) }}</dd></div><div><dt>Limit</dt><dd>{{ money(selectedOrder.limitPriceMicros) }}</dd></div><div><dt>Reconciliation</dt><dd>{{ selectedOrder.reconciliation }}</dd></div><div><dt>OMS version</dt><dd>{{ selectedOrder.omsVersion ?? "n/a" }}</dd></div></dl><p v-else class="empty-state">No active orders</p></section></div><section class="fills-section" aria-labelledby="fills-heading"><header class="section-header"><h2 id="fills-heading">Executions</h2><span>{{ snapshot.fills.length }}</span></header><div class="table-scroll" tabindex="0" aria-label="Executions. Scroll horizontally for all columns."><table><thead><tr><th>Execution</th><th>Instrument</th><th>Side</th><th class="number">Quantity</th><th class="number">Price</th><th>Venue</th><th>Strategy</th><th>Liquidity</th><th>Time</th></tr></thead><tbody><tr v-for="fill in snapshot.fills" :key="fill.executionId"><th>{{ shortId(fill.executionId) }}</th><td>{{ fill.instrument }}</td><td :class="fill.side === 'buy' ? 'positive' : 'negative'">{{ fill.side }}</td><td class="number">{{ quantity(fill.quantityMicros) }}</td><td class="number">{{ money(fill.priceMicros) }}</td><td>{{ fill.venue }}</td><td>{{ strategyName(fill.strategy) }}</td><td>{{ fill.liquidity }}</td><td>{{ fill.executedAt }}</td></tr></tbody></table></div></section></section>

    <section v-else-if="activePane === 'signals'" class="pane-section" aria-labelledby="signals-heading"><header class="pane-heading"><div><h1 id="signals-heading">Signals</h1><span>{{ snapshot.signals.length }} candidates</span></div><time :datetime="snapshot.observedAt">Decision state</time></header><div class="signal-layout"><div class="signal-register" role="list"><button v-for="signal in snapshot.signals" :key="signal.id" :class="{ selected: selectedSignal?.id === signal.id }" @click="emit('selectSignal', signal.id)"><i :data-state="signal.state" aria-hidden="true"></i><span><strong>{{ signal.hypothesis }}</strong><small>{{ strategyName(signal.strategyId) }} · {{ signal.instrument }} · {{ signal.horizon }}</small></span><b>{{ percent(signal.posteriorBps) }}</b></button></div><article v-if="selectedSignal" class="signal-inspector"><header><div><h2>{{ selectedSignal.hypothesis }}</h2><span>{{ selectedSignal.instrument }} · {{ selectedSignal.state }}</span></div><strong>{{ percent(selectedSignal.posteriorBps) }}</strong></header><TimeSeriesChart v-if="selectedSignalSeries" :series="selectedSignalSeries" /><dl><div><dt>Trigger</dt><dd>{{ selectedSignal.trigger }}</dd></div><div><dt>Decision cut</dt><dd>{{ selectedSignal.decisionCut }}</dd></div><div><dt>Action</dt><dd>{{ selectedSignal.action }}</dd></div><div v-if="selectedSignal.blocker"><dt>Blocker</dt><dd class="negative">{{ selectedSignal.blocker }}</dd></div></dl><ol aria-label="Signal lineage"><li v-for="step in selectedSignal.lineage" :key="step">{{ step }}</li></ol></article><p v-else class="empty-state">No signal candidates</p></div></section>

    <section v-else-if="activePane === 'activity'" class="pane-section" aria-labelledby="activity-heading"><header class="pane-heading"><div><h1 id="activity-heading">Activity</h1><span>{{ snapshot.activity.length }} recent</span></div><time :datetime="snapshot.observedAt">Sequence {{ snapshot.sequence.toLocaleString() }}</time></header><div class="activity-table" role="table" aria-label="Recent OMS activity"><div class="activity-head" role="row"><span role="columnheader">Time</span><span role="columnheader">Category</span><span role="columnheader">Entity</span><span role="columnheader">Stage</span><span role="columnheader">Outcome</span></div><div v-for="item in snapshot.activity" :key="item.id" role="row" :data-severity="item.severity"><code role="cell">{{ item.occurredAt }}</code><strong role="cell">{{ item.category }}</strong><span role="cell">{{ item.entity }}</span><small role="cell">{{ item.stage }}</small><b role="cell">{{ item.outcome }}</b></div></div></section>

    <section v-else class="pane-section sources-section" aria-labelledby="sources-heading"><header class="pane-heading"><div><h1 id="sources-heading">Sources</h1><span>{{ snapshot.sources.length }} connected</span></div><button @click="emit('explore')">Open data explorer</button></header><ul><li v-for="source in snapshot.sources" :key="`${source.name}:${source.channel}`" :data-health="source.health"><i aria-hidden="true"></i><div><strong>{{ source.name }}</strong><span>{{ source.channel }}</span></div><dl><div><dt>Lag</dt><dd>{{ source.lagMs.toLocaleString() }}ms</dd></div><div><dt>Watermark</dt><dd>{{ source.watermark }}</dd></div></dl><small>{{ source.detail }}</small></li></ul></section>
  </div>
</template>

<style scoped>
.operations-pane{min-width:0}.metric-strip{overflow-x:auto;border-bottom:1px solid var(--atlas-rule)}.metric-strip dl{display:grid;grid-template-columns:repeat(5,minmax(170px,1fr));min-width:850px;margin:0}.metric-strip dl>div{padding:16px 18px;border-right:1px solid var(--atlas-rule)}.metric-strip dl>div:last-child{border-right:0}.metric-strip dt,.section-header>span{color:var(--atlas-axis);font:9px var(--vp-font-family-mono);letter-spacing:.035em;text-transform:uppercase}.metric-strip dd{margin:7px 0 3px;font:620 20px var(--vp-font-family-mono);font-variant-numeric:tabular-nums;letter-spacing:-.025em}.metric-strip small{color:var(--atlas-muted);font-size:10px}.positive{color:var(--atlas-green-ink)!important}.negative,.caution{color:var(--atlas-oxide)!important}
.telemetry-section{border-bottom:1px solid var(--atlas-rule);background:var(--operator-black)}.section-header{display:flex;min-height:48px;justify-content:space-between;gap:16px;align-items:center;padding:0 16px;border-bottom:1px solid var(--atlas-rule)}.section-header h1,.section-header h2{margin:0;font-size:16px;font-weight:650;letter-spacing:-.01em}.metric-tabs{display:flex;align-self:stretch;overflow-x:auto}.metric-tabs button{position:relative;min-width:max-content;padding:0 11px;color:var(--atlas-axis);font:9px var(--vp-font-family-mono);border:0;background:transparent;cursor:pointer}.metric-tabs button[aria-selected=true]{color:var(--atlas-blue)}.metric-tabs button[aria-selected=true]::after{position:absolute;right:8px;bottom:0;left:8px;height:2px;content:"";background:var(--atlas-blue)}.account-register{border-bottom:1px solid var(--atlas-rule)}.account-register dl{display:grid;grid-template-columns:repeat(5,1fr);margin:0}.account-register dl>div{padding:12px 15px;border-right:1px solid var(--atlas-rule-soft)}.account-register dt{color:var(--atlas-axis);font:8px var(--vp-font-family-mono);text-transform:uppercase}.account-register dd{margin:6px 0 0;color:var(--atlas-ink);font:10px var(--vp-font-family-mono);text-transform:uppercase}
.pane-section{min-height:calc(100vh - 64px);background:var(--operator-black)}.pane-heading{display:flex;min-height:72px;justify-content:space-between;gap:20px;align-items:center;padding:0 20px;border-bottom:1px solid var(--atlas-rule)}.pane-heading>div{display:flex;gap:10px;align-items:baseline}.pane-heading h1{margin:0;font-size:24px;letter-spacing:-.025em}.pane-heading span,.pane-heading time{color:var(--atlas-axis);font:8px var(--vp-font-family-mono);text-transform:uppercase}.pane-heading>button{min-height:34px;padding:0 11px;color:var(--atlas-blue);font:8px var(--vp-font-family-mono);text-transform:uppercase;border:1px solid var(--atlas-rule);background:transparent;cursor:pointer}.position-summary{overflow-x:auto;border-bottom:1px solid var(--atlas-rule)}.position-summary dl{display:grid;grid-template-columns:repeat(4,minmax(180px,1fr));min-width:720px;margin:0}.position-summary dl>div{padding:15px 18px;border-right:1px solid var(--atlas-rule)}.position-summary dt{color:var(--atlas-axis);font:8px var(--vp-font-family-mono);text-transform:uppercase}.position-summary dd{margin:7px 0 0;font:620 18px var(--vp-font-family-mono);font-variant-numeric:tabular-nums}.table-scroll{overflow-x:auto}table{width:100%;min-width:980px;border-collapse:collapse}th,td{height:42px;padding:0 13px;color:var(--atlas-muted);font-size:10px;text-align:left;border-right:1px solid var(--atlas-rule-soft);border-bottom:1px solid var(--atlas-rule-soft)}thead th{height:31px;color:var(--atlas-axis);font:8px var(--vp-font-family-mono);letter-spacing:.035em;text-transform:uppercase;background:var(--atlas-surface-alt)}tbody th{color:var(--atlas-ink);font:610 11px var(--vp-font-family-mono)}.number{font-family:var(--vp-font-family-mono);font-variant-numeric:tabular-nums;text-align:right}.positions-table{min-width:1320px}.positions-table th:first-child{position:sticky;z-index:1;left:0;background:var(--operator-black)}.positions-table thead th:first-child{z-index:2;background:var(--atlas-surface-alt)}
.orders-grid{display:grid;grid-template-columns:minmax(390px,.92fr) minmax(380px,1.08fr);gap:14px;padding:14px;border-bottom:1px solid var(--atlas-rule)}.active-orders{min-width:0;border:1px solid var(--atlas-rule)}.order-register{display:grid}.order-register>button{display:grid;grid-template-columns:34px 72px auto;gap:4px 9px;align-items:center;min-height:56px;padding:8px 12px;text-align:left;border:0;border-bottom:1px solid var(--atlas-rule-soft);background:transparent;cursor:pointer}.order-register>button:hover,.order-register>button.selected{background:var(--atlas-blue-soft)}.order-register span{color:var(--atlas-oxide);font:8px var(--vp-font-family-mono);text-transform:uppercase}.order-register span[data-side=buy]{color:var(--atlas-green-ink)}.order-register strong{color:var(--atlas-ink);font:10px var(--vp-font-family-mono)}.order-register b{justify-self:end;color:var(--atlas-blue);font:500 8px var(--vp-font-family-mono);text-transform:uppercase}.order-register small{grid-column:2/4;overflow:hidden;color:var(--atlas-muted);font-size:9px;text-overflow:ellipsis;white-space:nowrap}.order-register code{grid-column:1;grid-row:2;color:var(--atlas-axis);font-size:7px}.order-detail{display:grid;grid-template-columns:repeat(3,1fr);margin:0;border-top:1px solid var(--atlas-rule)}.order-detail>div{padding:10px 12px;border-right:1px solid var(--atlas-rule-soft);border-bottom:1px solid var(--atlas-rule-soft)}.order-detail dt{color:var(--atlas-axis);font:8px var(--vp-font-family-mono);text-transform:uppercase}.order-detail dd{margin:5px 0 0;color:var(--atlas-ink);font:9px var(--vp-font-family-mono)}.ticket-loading{display:grid;min-height:380px;place-items:center;color:var(--atlas-axis);font:8px var(--vp-font-family-mono);text-transform:uppercase;border:1px solid var(--atlas-rule)}.fills-section{border-bottom:1px solid var(--atlas-rule)}
.activity-table{overflow-x:auto}.activity-table>div{display:grid;grid-template-columns:120px 90px minmax(150px,1fr) minmax(160px,.8fr) 120px;gap:12px;align-items:center;min-width:760px;min-height:52px;padding:0 16px;border-bottom:1px solid var(--atlas-rule-soft)}.activity-table .activity-head{min-height:32px;color:var(--atlas-axis);font:8px var(--vp-font-family-mono);text-transform:uppercase;background:var(--atlas-surface-alt)}.activity-table code,.activity-table small,.activity-table b{color:var(--atlas-axis);font:500 8px var(--vp-font-family-mono)}.activity-table strong{color:var(--atlas-blue);font:8px var(--vp-font-family-mono);text-transform:uppercase}.activity-table span{color:var(--atlas-ink);font-size:10px}.activity-table b{justify-self:end;color:var(--atlas-green-ink);text-transform:uppercase}.activity-table>div[data-severity=warning] b{color:var(--atlas-oxide)}
.signal-layout{display:grid;grid-template-columns:minmax(280px,.62fr) minmax(0,1.38fr);min-height:calc(100vh - 136px);background:var(--operator-black)}.signal-register{border-right:1px solid var(--atlas-rule)}.signal-register button{display:grid;grid-template-columns:8px minmax(0,1fr) auto;gap:10px;align-items:start;width:100%;min-height:72px;padding:13px 14px;text-align:left;border:0;border-bottom:1px solid var(--atlas-rule-soft);background:transparent;cursor:pointer}.signal-register button:hover,.signal-register button.selected{background:var(--atlas-blue-soft)}.signal-register i{width:7px;height:7px;margin-top:3px;border-radius:50%;background:var(--atlas-blue)}.signal-register i[data-state=eligible]{background:var(--atlas-green)}.signal-register i[data-state=blocked]{background:var(--atlas-oxide)}.signal-register span{display:grid;gap:5px;min-width:0}.signal-register strong{overflow:hidden;color:var(--atlas-ink);font-size:11px;text-overflow:ellipsis;white-space:nowrap}.signal-register small{overflow:hidden;color:var(--atlas-axis);font:8px var(--vp-font-family-mono);text-overflow:ellipsis;white-space:nowrap}.signal-register b{color:var(--atlas-green-ink);font:11px var(--vp-font-family-mono)}.signal-inspector{min-width:0;padding:18px}.signal-inspector>header{display:flex;justify-content:space-between;align-items:flex-start;gap:20px}.signal-inspector h2{margin:0;font-size:16px}.signal-inspector header span{color:var(--atlas-muted);font:8px var(--vp-font-family-mono);text-transform:uppercase}.signal-inspector header>strong{color:var(--atlas-green-ink);font:24px var(--vp-font-family-mono)}.signal-inspector dl{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));margin:4px 0 0;border:1px solid var(--atlas-rule)}.signal-inspector dl>div{min-width:0;padding:9px;border-right:1px solid var(--atlas-rule-soft)}.signal-inspector dt{color:var(--atlas-axis);font:8px var(--vp-font-family-mono);text-transform:uppercase}.signal-inspector dd{overflow:hidden;margin:5px 0 0;color:var(--atlas-muted);font-size:9px;text-overflow:ellipsis;white-space:nowrap}.signal-inspector ol{display:flex;flex-wrap:wrap;margin:12px 0 0;padding:0;list-style:none}.signal-inspector li{color:var(--atlas-blue);font:8px var(--vp-font-family-mono)}.signal-inspector li:not(:last-child)::after{margin:0 7px;color:var(--atlas-axis);content:"→"}
.sources-section ul{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));margin:0;padding:0;list-style:none}.sources-section li{display:grid;grid-template-columns:8px minmax(0,1fr) auto;gap:8px 10px;align-items:center;min-height:96px;padding:14px 16px;border-right:1px solid var(--atlas-rule-soft);border-bottom:1px solid var(--atlas-rule-soft)}.sources-section li>i{width:7px;height:7px;border-radius:50%;background:var(--atlas-green)}.sources-section li[data-health=degraded]>i,.sources-section li[data-health=stale]>i{background:var(--atlas-oxide)}.sources-section li>div{display:grid;gap:3px}.sources-section strong{font-size:11px}.sources-section span,.sources-section small{color:var(--atlas-muted);font:8px var(--vp-font-family-mono)}.sources-section li>dl{display:grid;gap:4px;margin:0}.sources-section li>dl div{display:flex;justify-content:space-between;gap:8px}.sources-section dt,.sources-section dd{margin:0;color:var(--atlas-axis);font:7px var(--vp-font-family-mono);text-transform:uppercase}.sources-section dd{color:var(--atlas-muted)}.sources-section li>small{grid-column:2/-1}.empty-state{display:grid;min-height:80px;place-items:center;margin:0;color:var(--atlas-axis);font:9px var(--vp-font-family-mono);text-transform:uppercase}
button:focus-visible,.table-scroll:focus-visible{outline:2px solid var(--atlas-blue);outline-offset:-2px}@media(max-width:1180px){.orders-grid{grid-template-columns:1fr}.active-orders{min-height:330px}}@media(max-width:820px){.signal-layout{grid-template-columns:1fr}.signal-register{border-right:0;border-bottom:1px solid var(--atlas-rule)}.signal-inspector dl{grid-template-columns:repeat(2,1fr)}.account-register{overflow-x:auto}.account-register dl{min-width:700px}}@media(max-width:620px){.pane-section{min-height:calc(100vh - 146px)}.pane-heading{min-height:64px;padding:0 13px}.pane-heading h1{font-size:21px}.pane-heading time{display:none}.metric-strip dl{min-width:760px}.section-header{align-items:flex-start;flex-direction:column;height:auto;min-height:60px;padding:12px}.metric-tabs{width:100%}.metric-tabs button{min-height:36px;padding:7px 10px}.orders-grid{gap:10px;padding:10px}.signal-inspector{padding:14px 12px}.signal-inspector>header{align-items:flex-end}.signal-inspector dl{grid-template-columns:1fr}.signal-inspector dl>div{border-right:0;border-bottom:1px solid var(--atlas-rule-soft)}.order-detail{grid-template-columns:repeat(2,1fr)}.activity-table>div{min-width:650px}.pane-heading>button{min-height:44px}.sources-section ul{grid-template-columns:1fr}}
</style>
